#!/usr/bin/env bash

set -eu

internalDocsUrl="https://internal-docs.dev.crg.one/api/specs"
name="supplier-hub-2"
title="supplier-hub-2"
contentFile="./docs/swagger.json"

content=$(cat $contentFile)

payload=$(jq -c -n \
	--arg name "$name" \
	--arg title "$title" \
	--arg content "$content" \
	'{name: $name, title: $title, content: $content}'
)

curl -v \
	-H "Content-Type: application/json" \
	-d "$payload" \
	"$internalDocsUrl"