definitions:
  models.Request:
    properties:
      artist:
        type: string
      price:
        type: number
      title:
        type: string
    required:
    - artist
    - price
    - title
    type: object
  models.Response:
    properties:
      artist:
        type: string
      id:
        type: string
      price:
        type: number
      title:
        type: string
    required:
    - artist
    - id
    - price
    - title
    type: object
info:
  contact: {}
paths:
  /example/albums:
    get:
      description: Get All Albums
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Response'
            type: array
      summary: Get Albums
      tags:
      - album
    post:
      consumes:
      - application/json
      description: Add a new Album
      parameters:
      - description: Album Data
        in: body
        name: album
        required: true
        schema:
          $ref: '#/definitions/models.Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
      summary: Create Album
      tags:
      - album
swagger: "2.0"
